name: Install and run tests

on: [push, pull_request] 

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install 'ruff==0.11.11'

      - name: Run Ruff
        run: ruff check . --output-format=github
  
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.11"
            jax-spec: "jax==0.5.3"
            label: "py311-jax053"
          - python-version: "3.11"
            jax-spec: "jax"
            label: "py311-latest"
          - python-version: "3.12"
            jax-spec: "jax"
            label: "py312-latest"
          - python-version: "3.13"
            jax-spec: "jax"
            label: "py313-latest"
        
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '${{ matrix.jax-spec }}'
          pip install . 

      - name: Run pytest
        run: |
          pip install pytest
          XLA_FLAGS=--xla_force_host_platform_device_count=4 python -m pytest tests/ --junitxml=junit/test-results-${{ matrix.label }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.label }}
          path: junit/test-results-${{ matrix.label }}.xml
        if: ${{ always() }}
